### ISSUE TITLE
remove notification to the arrow dev mail list

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-ballista-python#5]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

each action in this repo will trigger a mail to the arrow dev mail list, can we remove this action?
@andygrove 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kou** [comment]
Really?
We're use `issues@` not `dev@`:
* https://github.com/apache/arrow-ballista-python/blob/main/.asf.yaml#L38-L42
* https://lists.apache.org/list.html?dev@arrow.apache.org

**Comment by liukun4515** [comment]
> 



> Really? We're using `issues@` not `dev@`:
> 
> * https://github.com/apache/arrow-ballista-python/blob/main/.asf.yaml#L38-L42
> * https://lists.apache.org/list.html?dev@arrow.apache.org

yes, i received in 2023-02-03.
Did not receive email from 2023-02-03

**Comment by kou** [comment]
Ah, I've changed the configuration by #2.
