### ISSUE TITLE
Use correct attribution in footer of documentation pages

### ISSUE THREAD

**Issue by alamb** [apache/arrow-ballista-python#64]
### Is your feature request related to a problem or challenge?

To be inline with ASF policy, we should update the text in the footer used in the docs  to match the footer used in the main website (https://arrow.apache.org/). i.e. add the trademark attribution test.

I am not sure where the docs are hosted

**Comment by andygrove** [comment]
This is completed: 

https://arrow.apache.org/ballista/user-guide/python.html
